const baseRecipes=[
{name:'Lasanha à Bolonhesa',cat:'Almoços',time:'1h 20min',serves:'8 porções',image:'https://images.unsplash.com/photo-1574868235872-2c6f6eaf3d61?auto=format&fit=crop&w=700&q=85',tags:['massa','família'],fav:true,memory:'A receita que reúne todo mundo à mesa.'},
{name:'Frango na Panela',cat:'Jantares',time:'40 min',serves:'6 porções',image:'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=85',tags:['frango','almoço'],fav:false,memory:'Dourar bem o frango antes de colocar o caldo.'},
{name:'Bolo de Chocolate',cat:'Sobremesas',time:'50 min',serves:'10 porções',image:'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=700&q=85',tags:['sobremesa','família'],fav:true,memory:'Fiz no aniversário e não sobrou nada.'},
{name:'Macarrão à Carbonara',cat:'Jantares',time:'25 min',serves:'2 porções',image:'https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&w=700&q=85',tags:['massa'],fav:false,memory:'Usar bastante pimenta-do-reino moída na hora.'},
{name:'Picanha na Churrasqueira',cat:'Almoços',time:'40 min',serves:'6 porções',image:'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=700&q=85',tags:['carne','especial'],fav:false,memory:'Domingo de churrasco com a família.'},
{name:'Salada Caesar',cat:'Saudáveis',time:'15 min',serves:'2 porções',image:'https://images.unsplash.com/photo-1546793665-c74683f339c1?auto=format&fit=crop&w=700&q=85',tags:['leve','rápido'],fav:false,memory:''},
{name:'Pudim de Leite',cat:'Sobremesas',time:'1 h',serves:'8 porções',image:'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=700&q=85',tags:['doce'],fav:false,memory:''},
{name:'Suco de Laranja Natural',cat:'Bebidas',time:'5 min',serves:'2 porções',image:'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=700&q=85',tags:['fresco'],fav:false,memory:''}
];
let recipes=JSON.parse(localStorage.getItem('fabioRecipes')||'null')||baseRecipes;let currentView='inicio';let query='';
const app=document.getElementById('app');
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function card(r,i){return `<article class="recipe-card" data-recipe="${i}"><div class="recipe-image" style="background-image:url('${r.image}')"><button class="heart" data-fav="${i}" aria-label="Favoritar">${r.fav?'♥':'♡'}</button></div><div class="recipe-body"><h3>${esc(r.name)}</h3><div class="meta"><span>◷ ${esc(r.time||'—')}</span><span>♙ ${esc(r.serves||'—')}</span></div><div class="tags">${(r.tags||[]).map(t=>`<span class="tag">#${esc(t)}</span>`).join('')}</div></div></article>`}
function visible(){let r=recipes.filter(x=>`${x.name} ${x.cat} ${(x.tags||[]).join(' ')}`.toLowerCase().includes(query.toLowerCase()));if(currentView==='favoritas')r=r.filter(x=>x.fav);if(currentView==='testar')r=r.filter(x=>x.testar);if(currentView==='categorias')return r;return r}
function home(){let featured=recipes.slice(0,3),recent=recipes.slice(3,8);return `<div class="page"><section class="hero"><div><h1>Bem-vindo ao<br><em>Diário de Receitas<br>do Fábio</em></h1><p>Aqui cada receita tem um sabor especial<br>e uma história para contar.</p></div></section><div class="section-head"><h2>Receitas em destaque</h2><button class="link-button" data-view="receitas">Ver todas →</button></div><div class="dashboard-grid"><div><div class="cards">${featured.map((r,i)=>card(r,i)).join('')}</div><div class="section-head"><h2>Minhas últimas receitas</h2><button class="link-button" data-view="receitas">Ver todas →</button></div><div class="recent">${recent.map((r,i)=>`<div class="recent-row" data-recipe="${i+3}"><div class="recent-thumb" style="background-image:url('${r.image}')"></div><div><strong>${esc(r.name)}</strong><small>◷ ${r.time}　♙ ${r.serves}</small></div><span style="margin-left:auto;color:#947f75">•••</span></div>`).join('')}</div></div><div class="side-column"><div class="quote-card"><p>“Cozinhar é transformar ingredientes simples em momentos inesquecíveis.” ♡</p><button class="primary" id="newRecipe">＋ Nova receita</button></div><div class="quick"><h3>Ferramentas rápidas</h3><div class="quick-grid"><button id="listen"><span>◉</span>Ouvir receita<small>Escute o passo a passo</small></button><button id="timer"><span>◴</span>Temporizador<small>Cronometre suas receitas</small></button><button data-view="compras"><span>🛒</span>Lista de compras<small>Adicione ingredientes</small></button><button id="newRecipe2"><span>▣</span>Importar por foto<small>Transforme fotos em receitas</small></button></div></div></div></div></div>`}
function listView(){let title={receitas:'Minhas receitas',favoritas:'Receitas favoritas',testar:'Quero testar',categorias:'Categorias'}[currentView]||'Receitas';let data=visible();if(currentView==='categorias')return `<div class="page"><h1 class="view-title">Categorias</h1><p class="muted">Organize o diário do seu jeito.</p><div class="cards">${['Almoços','Jantares','Sobremesas','Bebidas','Saudáveis','Massas'].map(c=>`<button class="recipe-card" style="padding:30px;text-align:left" data-cat="${c}"><span style="font-size:28px;color:var(--wine)">✦</span><h3>${c}</h3><small>${recipes.filter(r=>r.cat===c).length} receitas guardadas</small></button>`).join('')}</div></div>`;return `<div class="page"><div class="toolbar"><div><h1 class="view-title">${title}</h1><p class="muted">${data.length} receitas no seu diário</p></div><button class="primary" id="newRecipe">＋ Nova receita</button></div><div class="cards">${data.length?data.map(r=>card(r,recipes.indexOf(r))).join(''):`<div class="empty">Ainda não há receitas aqui.<br><button class="primary" id="newRecipe" style="margin-top:18px">Adicionar receita</button></div>`}</div></div>`}
function shopping(){return `<div class="page"><h1 class="view-title">Lista de compras</h1><p class="muted">Ingredientes separados para deixar a próxima receita mais fácil.</p><div class="shopping"><div class="panel"><h2 style="font:24px 'Playfair Display'">Para o fim de semana</h2>${['Tomates maduros','Carne moída','Queijo muçarela','Manjericão fresco','Chocolate meio amargo','Ovos'].map((x,i)=>`<label class="check"><input type="checkbox" ${i===2?'checked':''}> ${x}</label>`).join('')}</div><div class="panel"><h3 style="font:21px 'Playfair Display'">Dica do diário</h3><p class="muted">Escolha uma receita e adicione os ingredientes que estão faltando à sua lista.</p><button class="primary" data-view="receitas">Escolher receita</button></div></div></div>`}
function render(){app.innerHTML=currentView==='inicio'?home():currentView==='compras'?shopping():listView();bind();}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===currentView));document.querySelector('.sidebar').classList.remove('open');render()});document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();recipes[+b.dataset.fav].fav=!recipes[+b.dataset.fav].fav;localStorage.setItem('fabioRecipes',JSON.stringify(recipes));render()});document.querySelectorAll('[data-recipe]').forEach(x=>x.onclick=()=>cook(+x.dataset.recipe));document.querySelectorAll('[data-cat]').forEach(x=>x.onclick=()=>{query=x.dataset.cat;currentView='receitas';document.querySelector('.sidebar').classList.remove('open');render()});document.querySelectorAll('#newRecipe,#newRecipe2').forEach(x=>x.onclick=()=>document.getElementById('modal').classList.add('open'));let l=document.getElementById('listen');if(l)l.onclick=()=>speak('Bem-vindo ao Diário de Receitas do Fábio. Escolha uma receita para começar.');let t=document.getElementById('timer');if(t)t.onclick=()=>{let m=prompt('Quantos minutos?','10');if(m){alert(`Temporizador iniciado por ${m} minutos.`)}}}
function cook(i){let r=recipes[i];let steps=['Separe todos os ingredientes e organize a bancada.','Prepare os ingredientes conforme as quantidades da receita.','Cozinhe em fogo médio, mexendo com carinho.','Sirva e registre no diário como ficou.'];let box=document.createElement('div');box.className='modal-backdrop open';box.innerHTML=`<section class="modal"><button class="close">×</button><div class="eyebrow">MODO COZINHA</div><h2>${esc(r.name)}</h2><p class="muted">${r.time} · ${r.serves}</p><div class="panel" style="margin-top:18px;background:#fbf4ec"><h3 style="font:21px 'Playfair Display'">Passo a passo</h3>${steps.map((s,n)=>`<label class="check"><input type="checkbox"> <b>${n+1}.</b> ${s}</label>`).join('')}</div><button class="primary full" id="speak">🔊 Ouvir receita</button></section>`;document.body.appendChild(box);box.querySelector('.close').onclick=()=>box.remove();box.querySelector('#speak').onclick=()=>speak(steps.join(' '))}
function speak(text){if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text))}else alert(text)}
document.getElementById('searchInput').oninput=e=>{query=e.target.value;currentView=currentView==='inicio'?'receitas':currentView;render()};document.getElementById('closeModal').onclick=()=>document.getElementById('modal').classList.remove('open');document.getElementById('recipeForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);recipes.unshift({name:f.get('name'),cat:f.get('category'),time:f.get('time')||'—',serves:'a gosto',image:f.get('image')||'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=700&q=85',tags:['nova'],fav:false,memory:f.get('memory')});localStorage.setItem('fabioRecipes',JSON.stringify(recipes));document.getElementById('modal').classList.remove('open');e.target.reset();currentView='receitas';render()};document.getElementById('mobileMenu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');render();
