const defaultRecipes = [
  {name:'Lasanha à Bolonhesa',cat:'Almoços',time:'1h 20min',serves:'8 porções',image:'https://images.unsplash.com/photo-1574868235872-2c6f6eaf3d61?auto=format&fit=crop&w=700&q=85',tags:['massa','família'],fav:true,memory:'A receita que reúne todo mundo à mesa.',ingredients:'500 g de carne moída\n1 pacote de massa para lasanha\n500 g de muçarela\nMolho de tomate',prep:'Faça o molho, monte as camadas e asse até gratinar.'},
  {name:'Frango na Panela',cat:'Jantares',time:'40 min',serves:'6 porções',image:'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=85',tags:['frango','almoço'],fav:false,memory:'Dourar bem o frango antes de colocar o caldo.',ingredients:'1 kg de frango\n2 tomates\n1 cebola\nTemperos a gosto',prep:'Doure o frango, junte os temperos e cozinhe até ficar macio.'},
  {name:'Bolo de Chocolate',cat:'Sobremesas',time:'50 min',serves:'10 porções',image:'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=700&q=85',tags:['sobremesa','família'],fav:true,memory:'Fiz no aniversário e não sobrou nada.',ingredients:'3 ovos\n2 xícaras de farinha\n1 xícara de chocolate\n1 xícara de açúcar',prep:'Misture os ingredientes, coloque em forma untada e asse.'},
  {name:'Macarrão à Carbonara',cat:'Jantares',time:'25 min',serves:'2 porções',image:'https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&w=700&q=85',tags:['massa'],fav:false,memory:'Usar bastante pimenta-do-reino moída na hora.'},
  {name:'Picanha na Churrasqueira',cat:'Almoços',time:'40 min',serves:'6 porções',image:'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=700&q=85',tags:['carne','especial'],fav:false,memory:'Domingo de churrasco com a família.'},
  {name:'Salada Caesar',cat:'Saudáveis',time:'15 min',serves:'2 porções',image:'https://images.unsplash.com/photo-1546793665-c74683f339c1?auto=format&fit=crop&w=700&q=85',tags:['leve','rápido'],fav:false,memory:''},
  {name:'Pudim de Leite',cat:'Sobremesas',time:'1 h',serves:'8 porções',image:'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=700&q=85',tags:['doce'],fav:false,memory:''},
  {name:'Suco de Laranja Natural',cat:'Bebidas',time:'5 min',serves:'2 porções',image:'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=700&q=85',tags:['fresco'],fav:false,memory:''}
];
let recipes=JSON.parse(localStorage.getItem('fabioRecipes')||'null')||defaultRecipes;
let shopping=JSON.parse(localStorage.getItem('fabioShopping')||'null')||['Tomates maduros','Carne moída','Queijo muçarela','Manjericão fresco','Chocolate meio amargo','Ovos'].map((name,i)=>({name,done:i===2}));
let currentView='inicio', query='', editingIndex=null, timerInterval=null, audioContext=null;
const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const save=()=>{localStorage.setItem('fabioRecipes',JSON.stringify(recipes));localStorage.setItem('fabioShopping',JSON.stringify(shopping))};
function card(r,i){return `<article class="recipe-card" data-recipe="${i}"><div class="recipe-image" style="background-image:url('${r.image}')"><button class="heart" data-fav="${i}" aria-label="Favoritar">${r.fav?'♥':'♡'}</button></div><div class="recipe-body"><h3>${esc(r.name)}</h3><div class="meta"><span>◷ ${esc(r.time||'—')}</span><span>♙ ${esc(r.serves||'—')}</span></div><div class="tags">${(r.tags||[]).map(t=>`<span class="tag">#${esc(t)}</span>`).join('')}</div></div></article>`}
function visible(){let result=recipes.filter(r=>`${r.name} ${r.cat} ${(r.tags||[]).join(' ')}`.toLowerCase().includes(query.toLowerCase()));if(currentView==='favoritas')result=result.filter(r=>r.fav);if(currentView==='testar')result=result.filter(r=>r.testar);if(currentView==='lixeira')result=result.filter(r=>r.deleted);else result=result.filter(r=>!r.deleted);return result}
function home(){let featured=recipes.filter(r=>!r.deleted).slice(0,3),recent=recipes.filter(r=>!r.deleted).slice(3,8);return `<div class="page"><section class="hero"><div><h1>Bem-vindo ao<br><em>Diário de Receitas<br>do Fábio</em></h1><p>Aqui cada receita tem um sabor especial<br>e uma história para contar.</p></div></section><div class="section-head"><h2>Receitas em destaque</h2><button class="link-button" data-view="receitas">Ver todas →</button></div><div class="dashboard-grid"><div><div class="cards">${featured.map(r=>card(r,recipes.indexOf(r))).join('')}</div><div class="section-head"><h2>Minhas últimas receitas</h2><button class="link-button" data-view="receitas">Ver todas →</button></div><div class="recent">${recent.map(r=>`<div class="recent-row" data-recipe="${recipes.indexOf(r)}"><div class="recent-thumb" style="background-image:url('${r.image}')"></div><div><strong>${esc(r.name)}</strong><small>◷ ${r.time}　♙ ${r.serves}</small></div><span style="margin-left:auto;color:#947f75">•••</span></div>`).join('')}</div></div><div class="side-column"><div class="quote-card"><p>“Cozinhar é transformar ingredientes simples em momentos inesquecíveis.” ♡</p><button class="primary" id="newRecipe">＋ Nova receita</button></div><div class="quick"><h3>Ferramentas rápidas</h3><div class="quick-grid"><button id="listen"><span>◉</span>Ouvir receita<small>Escute o passo a passo</small></button><button id="timer"><span>◴</span>Temporizador<small>Cronometre suas receitas</small></button><button data-view="compras"><span>🛒</span>Lista de compras<small>Adicione ingredientes</small></button><button id="newRecipe2"><span>▣</span>Nova receita<small>Guarde um novo sabor</small></button></div></div></div></div></div>`}
function listView(){let titles={receitas:'Minhas receitas',favoritas:'Receitas favoritas',testar:'Quero testar',lixeira:'Lixeira'};let data=visible();return `<div class="page"><div class="toolbar"><div><h1 class="view-title">${titles[currentView]||'Receitas'}</h1><p class="muted">${data.length} receitas no seu diário</p></div><button class="primary" id="newRecipe">＋ Nova receita</button></div>${data.length?`<div class="cards">${data.map(r=>card(r,recipes.indexOf(r))).join('')}</div>`:`<div class="empty">Ainda não há receitas aqui.<br><button class="primary" id="newRecipe" style="margin-top:18px">Adicionar receita</button></div>`}</div>`}
function categories(){return `<div class="page"><h1 class="view-title">Categorias</h1><p class="muted">Organize o diário do seu jeito.</p><div class="cards">${['Almoços','Jantares','Sobremesas','Bebidas','Saudáveis','Massas'].map(c=>`<button class="recipe-card category-card" data-cat="${c}"><span style="font-size:28px;color:var(--wine)">✦</span><h3>${c}</h3><small>${recipes.filter(r=>r.cat===c&&!r.deleted).length} receitas guardadas</small></button>`).join('')}</div></div>`}
function shoppingView(){return `<div class="page"><div class="toolbar"><div><h1 class="view-title">Lista de compras</h1><p class="muted">Organize os ingredientes para a próxima receita.</p></div><button class="primary" id="addShopping">＋ Adicionar item</button></div><div class="shopping"><div class="panel shopping-list"><h2 style="font:24px 'Playfair Display'">Para o fim de semana</h2>${shopping.length?shopping.map((x,i)=>`<div class="shopping-item ${x.done?'done':''}"><input type="checkbox" data-check-shop="${i}" ${x.done?'checked':''}><span>${esc(x.name)}</span><button data-edit-shop="${i}" title="Editar">✎</button><button data-delete-shop="${i}" title="Apagar">×</button></div>`).join(''):'<div class="empty">Sua lista está vazia.</div>'}</div><div class="panel"><h3 style="font:21px 'Playfair Display'">Adicionar da receita</h3><p class="muted">Abra uma receita no Modo Cozinha e use os ingredientes para montar sua lista.</p><button class="primary" data-view="receitas">Escolher receita</button></div></div></div>`}
function special(){return `<div class="page"><div class="toolbar"><div><h1 class="view-title">Ocasiões especiais</h1><p class="muted">Receitas para os momentos que merecem ser lembrados.</p></div><button class="primary" data-view="receitas">Ver receitas</button></div><div class="occasion-grid"><button class="occasion" data-search="especial">✦<strong>Almoço em família</strong><small>Sabores para reunir todo mundo</small></button><button class="occasion" data-search="doce">♡<strong>Datas comemorativas</strong><small>Uma sobremesa para celebrar</small></button><button class="occasion" data-search="rápido">◷<strong>Receitas sem pressa</strong><small>Para cozinhar com calma</small></button></div></div>`}
function render(){app.innerHTML=currentView==='inicio'?home():currentView==='compras'?shoppingView():currentView==='categorias'?categories():currentView==='ocasioes'?special():listView();bind()}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;query='';document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===currentView));closeMenu();render()});document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();recipes[+b.dataset.fav].fav=!recipes[+b.dataset.fav].fav;save();render()});document.querySelectorAll('[data-recipe]').forEach(x=>x.onclick=()=>cook(+x.dataset.recipe));document.querySelectorAll('[data-cat]').forEach(x=>x.onclick=()=>{query=x.dataset.cat;currentView='receitas';closeMenu();render()});document.querySelectorAll('[data-search]').forEach(x=>x.onclick=()=>{query=x.dataset.search;currentView='receitas';render()});document.querySelectorAll('#newRecipe,#newRecipe2').forEach(x=>x.onclick=()=>openRecipeForm());let l=document.getElementById('listen');if(l)l.onclick=()=>speak('Bem-vindo ao Diário de Receitas do Fábio. Escolha uma receita para começar.');let t=document.getElementById('timer');if(t)t.onclick=startTimer;document.querySelectorAll('[data-check-shop]').forEach(x=>x.onchange=()=>{shopping[+x.dataset.checkShop].done=x.checked;save();render()});document.querySelectorAll('[data-edit-shop]').forEach(x=>x.onclick=()=>editShopping(+x.dataset.editShop));document.querySelectorAll('[data-delete-shop]').forEach(x=>x.onclick=()=>{shopping.splice(+x.dataset.deleteShop,1);save();render()});let add=document.getElementById('addShopping');if(add)add.onclick=()=>editShopping(-1)}
function upgradeModal(){let form=document.getElementById('recipeForm');if(!form||form.elements.ingredients)return;document.querySelector('#modal section').innerHTML=`<button class="close" id="closeModal">×</button><div class="eyebrow">NOVA MEMÓRIA À MESA</div><h2>Adicionar receita</h2><p class="muted">Registre um sabor para lembrar depois.</p><form id="recipeForm"><label>Nome da receita<input name="name" required placeholder="Ex.: Bolo de fubá da vó"></label><div class="form-grid"><label>Categoria<select name="category"><option>Almoços</option><option>Jantares</option><option>Sobremesas</option><option>Café da manhã</option><option>Bebidas</option><option>Saudáveis</option></select></label><label>Tempo de preparo<input name="time" placeholder="45 min"></label></div><div class="form-grid"><label>Rendimento<input name="serves" placeholder="Ex.: 6 porções"></label><label>Etiquetas<input name="tags" placeholder="família, rápido"></label></div><label>Imagem da receita (URL)<input name="image" placeholder="https://..."></label><label>Ingredientes<textarea name="ingredients" rows="4" placeholder="Um ingrediente por linha"></textarea></label><label>Modo de preparo<textarea name="prep" rows="4" placeholder="Descreva o passo a passo"></textarea></label><label>Memória ou observação<textarea name="memory" rows="3" placeholder="O que torna essa receita especial?"></textarea></label><button class="primary full" type="submit">Guardar no diário</button></form>`;document.getElementById('closeModal').onclick=()=>document.getElementById('modal').classList.remove('open')}
function openRecipeForm(index=null){upgradeModal();editingIndex=index;let r=index===null?{}:recipes[index];let form=document.getElementById('recipeForm');form.reset();form.elements.name.value=r.name||'';form.elements.category.value=r.cat||'Almoços';form.elements.time.value=r.time||'';form.elements.serves.value=r.serves||'';form.elements.image.value=r.image||'';form.elements.tags.value=(r.tags||[]).join(', ');form.elements.ingredients.value=r.ingredients||'';form.elements.prep.value=r.prep||'';form.elements.memory.value=r.memory||'';document.querySelector('#modal h2').textContent=index===null?'Adicionar receita':'Editar receita';document.querySelector('#modal .eyebrow').textContent=index===null?'NOVA MEMÓRIA À MESA':'EDITAR NO DIÁRIO';document.getElementById('modal').classList.add('open')}
function editShopping(index){let old=index<0?'':shopping[index].name;let value=prompt('Nome do item:',old);if(value&&value.trim()){if(index<0)shopping.push({name:value.trim(),done:false});else shopping[index].name=value.trim();save();render()}}
function cook(i){let r=recipes[i],steps=(r.prep||'Separe os ingredientes.\nPrepare a receita com calma.\nSirva e registre sua memória.').split('\n');let box=document.createElement('div');box.className='modal-backdrop open';box.innerHTML=`<section class="modal"><button class="close">×</button><div class="eyebrow">MODO COZINHA</div><h2>${esc(r.name)}</h2><p class="muted">${r.time} · ${r.serves}</p><h3>Ingredientes</h3><pre class="ingredients">${esc(r.ingredients||'Ingredientes não cadastrados.')}</pre><div class="panel" style="margin-top:14px;background:#fbf4ec"><h3 style="font:21px 'Playfair Display'">Passo a passo</h3>${steps.map((s,n)=>`<label class="check"><input type="checkbox"> <b>${n+1}.</b> ${esc(s)}</label>`).join('')}</div><button class="primary full" id="speak">🔊 Ouvir receita</button><div class="recipe-actions"><button class="ghost" id="editRecipe">✎ Editar</button><button class="danger" id="deleteRecipe">♲ Apagar receita</button></div></section>`;document.body.appendChild(box);box.querySelector('.close').onclick=()=>box.remove();box.onclick=e=>{if(e.target===box)box.remove()};box.querySelector('#speak').onclick=()=>speak(`${r.name}. ${steps.join(' ')}`);box.querySelector('#editRecipe').onclick=()=>{box.remove();openRecipeForm(i)};box.querySelector('#deleteRecipe').onclick=()=>{if(confirm('Enviar esta receita para a lixeira?')){recipes[i].deleted=true;save();box.remove();render()}}}
function startTimer(){let value=prompt('Quantos minutos você precisa?','10');if(value===null)return;let minutes=Number(value);if(!Number.isFinite(minutes)||minutes<=0){alert('Digite um tempo maior que zero.');return}try{audioContext=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume()}catch(e){}let end=Date.now()+Math.round(minutes*60000);localStorage.setItem('fabioTimer',JSON.stringify({end}));showTimer(end)}
function showTimer(end){if(timerInterval)clearInterval(timerInterval);let box=document.createElement('div');box.className='modal-backdrop open';box.innerHTML=`<section class="modal timer-modal"><button class="close" aria-label="Fechar">×</button><div class="eyebrow">TEMPORIZADOR DE COZINHA</div><h2>Tempo de preparo</h2><div id="timerDisplay" style="font:700 clamp(62px,16vw,100px) 'Playfair Display';color:var(--wine);text-align:center;margin:22px 0 10px">00:00</div><p class="muted" style="text-align:center">O contador continua salvo se você sair da página.</p><button class="primary full" id="cancelTimer">Parar temporizador</button></section>`;document.body.appendChild(box);let display=box.querySelector('#timerDisplay'),close=()=>{clearInterval(timerInterval);box.remove()};box.querySelector('.close').onclick=close;box.querySelector('#cancelTimer').onclick=()=>{localStorage.removeItem('fabioTimer');close()};function tick(){let left=Math.max(0,end-Date.now()),seconds=Math.ceil(left/1000),m=Math.floor(seconds/60),s=seconds%60;display.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;if(left<=0){clearInterval(timerInterval);localStorage.removeItem('fabioTimer');display.textContent='00:00';box.querySelector('.eyebrow').textContent='TEMPO CONCLUÍDO';notifyFinish();startAlarm(box)}}tick();timerInterval=setInterval(tick,250)}
function startAlarm(box){let ctx=audioContext;try{if(!ctx)ctx=new (window.AudioContext||window.webkitAudioContext)();ctx.resume();let start=Date.now();let beep=()=>{if(!document.body.contains(box)||Date.now()-start>=10000){return}let osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=880;gain.gain.value=.12;osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.18);setTimeout(beep,600)};beep()}catch(e){} }
function notifyFinish(){if('Notification'in window&&Notification.permission==='granted')new Notification('Diário de Receitas',{body:'Seu temporizador terminou.'});else if('Notification'in window&&Notification.permission==='default')Notification.requestPermission()}
function recoverTimer(){let saved=JSON.parse(localStorage.getItem('fabioTimer')||'null');if(saved&&saved.end>Date.now())showTimer(saved.end);else if(saved){localStorage.removeItem('fabioTimer');notifyFinish()}}
function formatTime(seconds){let m=Math.floor(seconds/60),s=seconds%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function speak(text){if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text))}else alert(text)}
function closeMenu(){document.querySelector('.sidebar').classList.remove('open')}
upgradeModal();document.getElementById('searchInput').oninput=e=>{query=e.target.value;currentView=currentView==='inicio'?'receitas':currentView;render()};document.getElementById('closeModal').onclick=()=>document.getElementById('modal').classList.remove('open');document.getElementById('recipeForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),data={name:f.get('name'),cat:f.get('category'),time:f.get('time')||'—',serves:f.get('serves')||'a gosto',image:f.get('image')||'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=700&q=85',tags:String(f.get('tags')||'').split(',').map(x=>x.trim()).filter(Boolean),ingredients:f.get('ingredients'),prep:f.get('prep'),memory:f.get('memory'),fav:editingIndex===null?false:recipes[editingIndex].fav};if(editingIndex===null)recipes.unshift(data);else recipes[editingIndex]={...recipes[editingIndex],...data};save();document.getElementById('modal').classList.remove('open');e.target.reset();currentView='receitas';render()};document.getElementById('mobileMenu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');document.querySelector('.content').addEventListener('click',e=>{if(window.innerWidth<=650&&!e.target.closest('.mobile-menu'))closeMenu()});window.addEventListener('resize',()=>{if(window.innerWidth>650)closeMenu()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();document.getElementById('modal').classList.remove('open')}});document.addEventListener('visibilitychange',()=>{if(!document.hidden){let saved=JSON.parse(localStorage.getItem('fabioTimer')||'null');if(saved&&saved.end<=Date.now()){localStorage.removeItem('fabioTimer');notifyFinish()}}});render();recoverTimer();
